on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --allow-redirect --allow-dupe --allow 302,429 --white-list www.vagrantup.com README.md
