on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: awesome_bot README.md --allow-redirect --allow-dupe --white-list www.vagrantup.com
